networks:
  blab:
    driver: bridge

services:
  kafka:
    image: bitnami/kafka
    networks:
      - blab
    ports:
      - 9092:9092
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_KRAFT_CLUSTER_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1

  connect:
    image: ghcr.io/blabtm/kafka-connect-base:0.0.1
    networks:
      - blab
    ports:
      - 8083:8083
    environment:
      - CONNECT_BOOTSTRAP_SERVERS=kafka:9092
      - CONNECT_GROUP_ID=connect
      - CONNECT_CONFIG_STORAGE_TOPIC=connect-config
      - CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR=1
      - CONNECT_OFFSET_STORAGE_TOPIC=connect-offsets
      - CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR=1
      - CONNECT_STATUS_STORAGE_TOPIC=connect-status
      - CONNECT_STATUS_STORAGE_REPLICATION_FACTOR=1
      - CONNECT_KEY_CONVERTER=org.apache.kafka.connect.converters.ByteArrayConverter
      - CONNECT_VALUE_CONVERTER=org.apache.kafka.connect.converters.ByteArrayConverter
      - CONNECT_REST_ADVERTISED_HOST_NAME=localhost
      - CONNECT_PLUGIN_PATH=/usr/share/java
      - CONNECT_PLUGINS=https://github.com/blabtm/kafka-connect-tcp/releases/download/0.0.1/kafka-connect-tcp-0.0.1-all.jar
    depends_on:
      - kafka
